"""dev

Revision ID: 0e4e72d82359
Revises: e7e5f3c4fdad
Create Date: 2022-10-01 23:10:23.794332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4e72d82359'
down_revision = 'e7e5f3c4fdad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leagueName', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamName', sa.String(length=140), nullable=True),
    sa.Column('headCoach', sa.Integer(), nullable=True),
    sa.Column('league', sa.Integer(), nullable=True),
    sa.Column('totalScore', sa.Integer(), nullable=True),
    sa.Column('totalScoreAgainst', sa.Integer(), nullable=True),
    sa.Column('totalWins', sa.Integer(), nullable=True),
    sa.Column('totalLosses', sa.Integer(), nullable=True),
    sa.Column('tournaments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['headCoach'], ['user.id'], ),
    sa.ForeignKeyConstraint(['league'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_teamName'), 'team', ['teamName'], unique=True)
    op.add_column('user', sa.Column('hashedPassword', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('firstName', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('lastName', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('phoneNumber', sa.String(length=64), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'phoneNumber')
    op.drop_column('user', 'address')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    op.drop_column('user', 'hashedPassword')
    op.drop_index(op.f('ix_team_teamName'), table_name='team')
    op.drop_table('team')
    op.drop_table('league')
    # ### end Alembic commands ###
