"""empty message

Revision ID: 0edaffc8f7ed
Revises: 31e00c80de8d
Create Date: 2022-10-13 19:11:00.889940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edaffc8f7ed'
down_revision = '31e00c80de8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coachApproveID', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('adminApproveID', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'adminApproveID')
    op.drop_column('user', 'coachApproveID')
    # ### end Alembic commands ###
