"""empty message

Revision ID: 31e00c80de8d
Revises: daffe95a924a
Create Date: 2022-10-13 15:34:26.268487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e00c80de8d'
down_revision = 'daffe95a924a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isCoach', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    op.drop_column('user', 'isCoach')
    # ### end Alembic commands ###
