"""empty message

Revision ID: 529cae902a89
Revises: 
Create Date: 2022-10-17 02:04:39.308419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529cae902a89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('league', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team', 'league', ['league'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'league')
    # ### end Alembic commands ###
