"""empty message

Revision ID: 6b024780b6f5
Revises: 661a356a1e0c
Create Date: 2022-10-11 11:56:09.478966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b024780b6f5'
down_revision = '661a356a1e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'tournamentPicture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('tournamentPicture', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
