"""empty message

Revision ID: 968ae0650023
Revises: 
Create Date: 2022-10-16 19:15:07.379608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968ae0650023'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'nonsense_prop')
    op.add_column('user', sa.Column('_is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('_is_coach', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_is_coach')
    op.drop_column('user', '_is_admin')
    op.add_column('team', sa.Column('nonsense_prop', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
