"""empty message

Revision ID: b2917b48cc92
Revises: be6910b2de64
Create Date: 2022-10-03 19:31:13.901358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2917b48cc92'
down_revision = 'be6910b2de64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.drop_index('ix_tournament_teamName', table_name='tournament')
    op.create_index(op.f('ix_tournament_tournamentDate'), 'tournament', ['tournamentDate'], unique=False)
    op.create_index(op.f('ix_tournament_tournamentName'), 'tournament', ['tournamentName'], unique=True)
    op.drop_column('tournament', 'tournaments')
    op.drop_column('tournament', 'totalLosses')
    op.drop_column('tournament', 'league')
    op.drop_column('tournament', 'teamName')
    op.drop_column('tournament', 'headCoach')
    op.drop_column('tournament', 'totalScoreAgainst')
    op.drop_column('tournament', 'totalScore')
    op.drop_column('tournament', 'totalWins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('totalWins', sa.INTEGER(), nullable=True))
    op.add_column('tournament', sa.Column('totalScore', sa.INTEGER(), nullable=True))
    op.add_column('tournament', sa.Column('totalScoreAgainst', sa.INTEGER(), nullable=True))
    op.add_column('tournament', sa.Column('headCoach', sa.INTEGER(), nullable=True))
    op.add_column('tournament', sa.Column('teamName', sa.VARCHAR(length=140), nullable=True))
    op.add_column('tournament', sa.Column('league', sa.INTEGER(), nullable=True))
    op.add_column('tournament', sa.Column('totalLosses', sa.INTEGER(), nullable=True))
    op.add_column('tournament', sa.Column('tournaments', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_tournament_tournamentName'), table_name='tournament')
    op.drop_index(op.f('ix_tournament_tournamentDate'), table_name='tournament')
    op.create_index('ix_tournament_teamName', 'tournament', ['teamName'], unique=False)
    op.drop_table('following')
    # ### end Alembic commands ###
