"""empty message

Revision ID: b5f960ba3b79
Revises: 
Create Date: 2022-10-15 19:35:46.365589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f960ba3b79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('team_name', sa.String(length=140), nullable=True))
    op.drop_index('ix_team_teamName', table_name='team')
    op.create_index(op.f('ix_team_team_name'), 'team', ['team_name'], unique=True)
    op.drop_constraint('team_league_fkey', 'team', type_='foreignkey')
    op.drop_constraint('team_headCoach_fkey', 'team', type_='foreignkey')
    op.drop_column('team', 'headCoach')
    op.drop_column('team', 'totalWins')
    op.drop_column('team', 'totalLosses')
    op.drop_column('team', 'league')
    op.drop_column('team', 'totalScore')
    op.drop_column('team', 'teamName')
    op.drop_column('team', 'totalScoreAgainst')
    op.drop_column('team', 'tournaments')
    op.drop_column('user', 'coachApproveID')
    op.drop_column('user', 'isAdmin')
    op.drop_column('user', 'isCoach')
    op.drop_column('user', 'adminApproveID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adminApproveID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('isCoach', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('isAdmin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('coachApproveID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('team', sa.Column('tournaments', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('team', sa.Column('totalScoreAgainst', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('team', sa.Column('teamName', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.add_column('team', sa.Column('totalScore', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('team', sa.Column('league', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('team', sa.Column('totalLosses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('team', sa.Column('totalWins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('team', sa.Column('headCoach', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('team_headCoach_fkey', 'team', 'user', ['headCoach'], ['id'])
    op.create_foreign_key('team_league_fkey', 'team', 'league', ['league'], ['id'])
    op.drop_index(op.f('ix_team_team_name'), table_name='team')
    op.create_index('ix_team_teamName', 'team', ['teamName'], unique=False)
    op.drop_column('team', 'team_name')
    # ### end Alembic commands ###
