"""test migrate

Revision ID: be6910b2de64
Revises: 0e4e72d82359
Create Date: 2022-10-02 11:30:47.425540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6910b2de64'
down_revision = '0e4e72d82359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournamentName', sa.String(length=140), nullable=True),
    sa.Column('tournamentDate', sa.DateTime(), nullable=True),
    sa.Column('tournamentLocation', sa.String(length=200), nullable=True),
    sa.Column('tournamentLeague', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournamentLeague'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_tournamentDate'), 'tournament', ['tournamentDate'], unique=False)
    op.create_index(op.f('ix_tournament_tournamentName'), 'tournament', ['tournamentName'], unique=True)
    op.create_table('following',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('following')
    op.drop_index(op.f('ix_tournament_tournamentName'), table_name='tournament')
    op.drop_index(op.f('ix_tournament_tournamentDate'), table_name='tournament')
    op.drop_table('tournament')
    # ### end Alembic commands ###
