"""empty message

Revision ID: d432b400bef4
Revises: b5f960ba3b79
Create Date: 2022-10-15 20:24:53.919115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd432b400bef4'
down_revision = 'b5f960ba3b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('user_is_coach', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'user_is_coach')
    # ### end Alembic commands ###
