"""empty message

Revision ID: daffe95a924a
Revises: 
Create Date: 2022-10-12 11:04:39.005973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daffe95a924a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leagueName', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('hashedPassword', sa.String(length=128), nullable=True),
    sa.Column('firstName', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=140), nullable=True),
    sa.Column('phoneNumber', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamName', sa.String(length=140), nullable=True),
    sa.Column('headCoach', sa.Integer(), nullable=True),
    sa.Column('league', sa.Integer(), nullable=True),
    sa.Column('totalScore', sa.Integer(), nullable=True),
    sa.Column('totalScoreAgainst', sa.Integer(), nullable=True),
    sa.Column('totalWins', sa.Integer(), nullable=True),
    sa.Column('totalLosses', sa.Integer(), nullable=True),
    sa.Column('tournaments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['headCoach'], ['user.id'], ),
    sa.ForeignKeyConstraint(['league'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_teamName'), 'team', ['teamName'], unique=True)
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournamentName', sa.String(length=140), nullable=True),
    sa.Column('tournamentDate', sa.DateTime(), nullable=True),
    sa.Column('tournamentLocation', sa.String(length=200), nullable=True),
    sa.Column('tournamentLeague', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournamentLeague'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_tournamentDate'), 'tournament', ['tournamentDate'], unique=False)
    op.create_index(op.f('ix_tournament_tournamentName'), 'tournament', ['tournamentName'], unique=True)
    op.create_table('following',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('following')
    op.drop_index(op.f('ix_tournament_tournamentName'), table_name='tournament')
    op.drop_index(op.f('ix_tournament_tournamentDate'), table_name='tournament')
    op.drop_table('tournament')
    op.drop_index(op.f('ix_team_teamName'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('league')
    # ### end Alembic commands ###
