"""empty message

Revision ID: f068bd50184e
Revises: 27b0848a967c
Create Date: 2022-10-19 12:43:43.605434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f068bd50184e'
down_revision = '27b0848a967c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=64), nullable=True))
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'hashedPassword')
    op.drop_column('user', 'phoneNumber')
    op.drop_column('user', 'firstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstName', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phoneNumber', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('hashedPassword', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('lastName', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
